### ISSUE TITLE
Token name inconsistency when removing liquidity

### ISSUE THREAD

**Issue by benber86** [pangolindex/interface#39] opened 2021-05-15 13:55 UTC
From Discord:

```When I remove liquidity from a Pangolin LP with AVAX as one side of the pair, it comes out as AVAX if I do a full withdrawal, but as WAVAX if I do a partial withdrawal. The latter is pretty confusing and makes the user think their coins went "poof".```

**Issue:**
Token names appear to be inconsistent depending on whether a user withdraws liquidity entirely (AVAX) or partially (WAVAX)

**Expected behavior:**
Token denomination is the same in both cases

**Comment by cryptonote-social** [comment] 2021-05-15 14:40
Hmm, actually I just did another test and withdrew complete liquidity and it still came out as WAVAX.  So I guess the issue is whether it should come out as WAVAX or AVAX?  Coming out as WAVAX is a bit confusing but I guess I can see an argument as to why it makes sense.

**Comment by HariSeldon23** [comment] 2021-06-02 23:49
Is this still an issue? Should we close this?

**Comment by cryptonote-social** [comment] 2021-06-03 02:09
I just withdrew liquidity today and it came out as wAVAX.... so yeah.  The fix might be as simple as making it clear when one is dealing with AVAX vs. WAVAX.

**Closed** 2021-12-13 09:33 UTC
